### ISSUE TITLE
Server error, unable to invoke inventory

### ISSUE THREAD

**Issue by purejosh** [Ellemes/container-library#21]
Fabric 1.18.2, through a velocity proxy. I believe the proxy is probably blocking that inventory call, but could we maybe get a config to omit these errors entirely? It doesn't appear to affect the storage capabilities of the plugin using the API, which is Expanded Storage. If it's not causing any issues, I don't see a reason to keep these in the log file. 

`[14:54:42] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@50b0526d, suppressing error
java.lang.NullPointerException: Cannot invoke "ninjaphenix.container_library.api.v2.OpenableBlockEntityV2.getInventoryTitle()" because "inventory" is null
	at ellemes.container_library.wrappers.NetworkWrapper.s_openInventory(NetworkWrapper.java:22) ~[ellemes-container-library-1.4.0-beta.2+1.18.2-fabric.jar:?]
	at ninjaphenix.container_library.api.v2.OpenableBlockEntityProviderV2.ncl_sOpenInventory(OpenableBlockEntityProviderV2.java:86) ~[ellemes-container-library-1.4.0-beta.2+1.18.2-fabric.jar:?]
	at ninjaphenix.container_library.api.v2.OpenableBlockEntityProviderV2.ncl_sOpenInventory(OpenableBlockEntityProviderV2.java:79) ~[ellemes-container-library-1.4.0-beta.2+1.18.2-fabric.jar:?]
	at ninjaphenix.container_library.api.v2.OpenableBlockEntityProviderV2.ncl_onBlockUse(OpenableBlockEntityProviderV2.java:49) ~[ellemes-container-library-1.4.0-beta.2+1.18.2-fabric.jar:?]
	at ellemes.expandedstorage.block.OpenableBlock.method_9534(OpenableBlock.java:90) ~[expandedstorage-7.4.0-beta.4+1.18.2-fabric.jar:?]
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:939) ~[server-intermediary.jar:?]
	at net.minecraft.class_3225.method_14262(class_3225.java:336) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12046(class_3244.java:1081) ~[server-intermediary.jar:?]
	at net.minecraft.class_2885.method_12547(class_2885.java:30) ~[server-intermediary.jar:?]
	at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:808) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:790) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:769) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by Ellemes** [comment]
I can't supress this as the code is failing, you should ask velocity proxy to fix this instead, however hopefully the next v3 api fixes this issue, I plan starting a backport to 1.18.2 as soon as it's released for 1.19.

**Comment by Seceroth** [comment]
Can confirm this also happens without Velocity.

Fabric API fabric-api-0.57.0+1.18.2
Ellemes-container-library v1.4.0-beta.2+1.18.2-fabric
Expandedstorage v7.4.0-beta.4+1.18.2-fabric
